# Generated by Django 3.2.9 on 2021-11-06 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Url',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
            ],
        ),
    ]
