# Generated by Django 3.2.9 on 2021-11-06 20:32

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('url', '0002_url_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url',
            name='id',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
