# Generated by Django 3.2.9 on 2021-11-06 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('url', '0004_auto_20211106_2036'),
    ]

    operations = [
        migrations.AddField(
            model_name='url',
            name='generated_url',
            field=models.URLField(),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='url',
            name='real_url',
            field=models.URLField(),
            preserve_default=False,
        ),
    ]
