# Generated by Django 3.2.9 on 2021-11-06 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('url', '0005_auto_20211106_2155'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='url',
            constraint=models.UniqueConstraint(fields=('generated_url', 'real_url'), name='urls'),
        ),
    ]
