# Generated by Django 3.2.9 on 2021-11-06 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('url', '0006_url_urls'),
    ]

    operations = [
        migrations.AddField(
            model_name='url',
            name='generated_part',
            field=models.CharField(default=323, max_length=5),
            preserve_default=False,
        ),
    ]
